class MembershipPlans(models.Model):
    membership_plan_id = models.BigAutoField(primary_key=True)
    product_type = models.IntegerField(blank=True, null=True)
    plan_type = models.IntegerField(blank=True, null=True)
    user_type = models.IntegerField(blank=True, null=True)
    selling_amount = models.FloatField(blank=True, null=True)
    actual_amount = models.FloatField(blank=True, null=True)
    duration = models.CharField(max_length=245, blank=True, null=True)
    no_of_workout = models.CharField(max_length=245, blank=True, null=True)
    plan_free_type = models.IntegerField(blank=True, null=True)
    plan_free_duration = models.CharField(max_length=245, blank=True, null=True)
    is_active = models.CharField(max_length=3, blank=True, null=True)
    studio_category = models.IntegerField(blank=True, null=True)
    team_zone_name = models.CharField(max_length=245, blank=True, null=True)
    created_by = models.CharField(max_length=145, blank=True, null=True)
    updated_by = models.CharField(max_length=145, blank=True, null=True)
    create_time = models.DateTimeField(blank=True, null=True)
    update_time = models.DateTimeField(blank=True, null=True)
    offer_name = models.CharField(max_length=245, blank=True, null=True)
    offer_type = models.CharField(max_length=245, blank=True, null=True)
    is_redeem = models.CharField(max_length=3, blank=True, null=True)
    discount_amount = models.CharField(max_length=245, blank=True, null=True)
    coupon_type = models.CharField(max_length=245, blank=True, null=True)
    coupon_name = models.CharField(max_length=245, blank=True, null=True)
    coupon_id = models.IntegerField(blank=True, null=True)
    upgrade_membership_amount = models.FloatField(blank=True, null=True)
    lat_long = models.CharField(max_length=245, blank=True, null=True)
    plan_deeplink_url = models.TextField(blank=True, null=True)
    subscription_id = models.TextField(blank=True, null=True)
    corporate_id = models.IntegerField(blank=True, null=True)
    tax_applicable = models.IntegerField(blank=True, null=True)
    about_plan = models.TextField(blank=True, null=True)
    tax_applicable_amount = models.TextField(blank=True, null=True)
    membership_price = models.FloatField(blank=True, null=True)
    user_can_redeem = models.IntegerField(blank=True, null=True)
    user_can_apply_coupon = models.IntegerField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    total_payment_count = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'fitpass_membership_plans'

