class TransactionHistory(models.Model):
    transaction_history_id = models.BigAutoField(primary_key=True)
    total_order_price = models.FloatField()
    received_order_price = models.FloatField()
    product_type = models.IntegerField()
    order_date = models.DateTimeField(blank=True, null=True)
    customer_name = models.CharField(max_length=245, blank=True, null=True)
    user_membership_id = models.CharField(max_length=245, blank=True, null=True)
    user_id = models.BigIntegerField()
    request_header = models.TextField(blank=True, null=True)
    transaction_number = models.TextField(blank=True, null=True)
    created_by = models.CharField(max_length=145, blank=True, null=True)
    order_details = models.TextField(blank=True, null=True)
    transaction_month = models.CharField(max_length=8, blank=True, null=True)
    tax = models.CharField(max_length=45, blank=True, null=True)
    team_zone_name = models.CharField(max_length=245, blank=True, null=True)
    coupon_code = models.CharField(max_length=245, blank=True, null=True)
    transaction_source = models.CharField(max_length=245, blank=True, null=True)
    is_active = models.CharField(max_length=3, blank=True, null=True)
    last_team_response = models.TextField(blank=True, null=True)
    membership_transfer_from_zone_name = models.CharField(max_length=245, blank=True, null=True)
    membership_transfer_to_zone_name = models.CharField(max_length=245, blank=True, null=True)
    membership_transfer_from_zone = models.CharField(max_length=245, blank=True, null=True)
    membership_transfer_zone = models.CharField(max_length=245, blank=True, null=True)
    membership_transfer_remarks = models.TextField(blank=True, null=True)
    payments_details = models.TextField(blank=True, null=True)
    user_source = models.CharField(max_length=45, blank=True, null=True)
    payments_settlement_details = models.TextField(blank=True, null=True)
    payment_gateway_id = models.TextField(blank=True, null=True)
    payments_active_from = models.CharField(max_length=245, blank=True, null=True)
    membership_transfer_date = models.DateTimeField(blank=True, null=True)
    product_cycle = models.TextField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    membership_transfer_from_product_type = models.IntegerField(blank=True, null=True)
    app_version = models.CharField(max_length=45, blank=True, null=True)
    device_type = models.TextField(blank=True, null=True)
    device_name = models.TextField(blank=True, null=True)
    transaction_type = models.CharField(max_length=245, blank=True, null=True)
    lead_follower_team_member_id = models.CharField(max_length=45, blank=True, null=True)
    membership_plan_id = models.IntegerField(blank=True, null=True)
    corporate_id = models.IntegerField(blank=True, null=True)
    user_type = models.IntegerField(blank=True, null=True)
    total_discount = models.FloatField(blank=True, null=True)
    coupon_discount = models.FloatField(blank=True, null=True)
    redeem_points = models.FloatField(blank=True, null=True)
    fitprime_price = models.FloatField(blank=True, null=True)
    referral_channel = models.TextField(blank=True, null=True)
    user_preferred_city = models.CharField(max_length=45, blank=True, null=True)
    is_subscription = models.IntegerField(blank=True, null=True)
    fitcard_agents_id = models.IntegerField(blank=True, null=True)
    task_management = models.ForeignKey('TaskManagement', models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'fitpass_transaction_history'


