AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FileParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.amazonaws.handlers.FileParserHandler::handleRequest
      Timeout: 60
      CodeUri: s3://com.pratik.test.bucket/aws-serverless-java/com.amazonaws.parsefile:JavaExcelFileParser:1.0-SNAPSHOT/24906065720c3d6e3c208cb7fe1fc33c
      Role: arn:aws:iam::953636143786:role/S3FullAccessRole
      Events:
        CSVFileUploadedEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: SrcBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: test/
  SrcBucket:
    Type: AWS::S3::Bucket
