version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "UserApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ktq56jeti5by"
s3_prefix = "UserApi"
region = "ap-south-1"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "DaciaServicePrincipalSuffix=\"dacia_aws_internal\""

